refactor: Use GistManager class in Checker class
feat: Implement GistManager class for Gist API interactions

refactor: Rename scheduleRun.yml to Schedule Python Script Execution

diff --git a/.github/workflows/cron_run_main.yml b/.github/workflows/cron_run_main.yml
--- a/.github/workflows/cron_run_main.yml
+++ b/.github/workflows/cron_run_main.yml
@@ -1,4 +1,4 @@
-name: scheduleRun
+name: Schedule Python Script Execution
 
 on:
   schedule:
@@ -9,29 +9,30 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      - name: Checkout code
+      - name: Checkout Repository
         uses: actions/checkout@v3
 
-      - name: Set up Python
+      - name: Set up Python 3.12
         uses: actions/setup-python@v3
         with:
           python-version: "3.12"
 
-      - name: Cache dependencies
+      - name: Cache Python Dependencies
         uses: actions/cache@v3
         with:
           path: ~/.cache/pip
-          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
+          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}-3.12
+
           restore-keys: |
             ${{ runner.os }}-pip-
 
-      - name: Upgrade pip
+      - name: Upgrade pip to Latest Version
         run: python -m pip install --upgrade pip
 
-      - name: Install dependencies
-        run: pip install -r requirements.txt
+      - name: Install Python Dependencies
+        run: pip install --no-cache-dir -r requirements.txt
 
-      - name: Run main.py
+      - name: Run Python Script
         env:
           TELEGRAM_API_TOKEN: ${{ secrets.TELEGRAM_API_TOKEN }}
           TELEGRAM_CHAT_ID_1: ${{ secrets.TELEGRAM_CHAT_ID_1 }}
@@ -44,4 +45,5 @@ jobs:
           LANGCHAIN_ENDPOINT: ${{ secrets.LANGCHAIN_ENDPOINT }}
           LANGCHAIN_API_KEY: ${{ secrets.LANGCHAIN_API_KEY }}
           LANGCHAIN_PROJECT: ${{ secrets.LANGCHAIN_PROJECT }}
-        run: python main.py
+        run: |
+          python main.py || echo "main.py failed"
